repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check via Maven
        entry: bash -c "cd app && mvn spotless:check"
        language: system
        types: [java]
